FROM golang:1.20.4-alpine
WORKDIR /srv/knoq

RUN go install github.com/cosmtrek/air@latest

COPY go.mod ./
COPY go.sum ./
ENV GO111MODULE=on
RUN go mod download
COPY ./ ./

ENTRYPOINT ["air", "-c", ".air.toml"]
