# syntax=docker/dockerfile:1

# for development (with live reload)

FROM golang:1-alpine
WORKDIR /srv/knoq

COPY go.mod ./
COPY go.sum ./
ENV GO111MODULE=on
RUN go mod download
COPY ./ ./

RUN mkdir -p ./web/dist \
  && apk add --no-cache curl \
  && curl -L -Ss https://github.com/traPtitech/knoQ-UI/releases/latest/download/dist.tar.gz \
  | tar zxv -C ./web
RUN touch ./service.json

RUN go install github.com/cosmtrek/air@latest

ENTRYPOINT ["air", "-c", ".air.toml"]
