// Code generated by gotypeconverter; DO NOT EDIT.
package v8

func ConvSEventAdminToSRoomAdmin(src []EventAdmin) (dst []RoomAdmin) {
	dst = make([]RoomAdmin, len(src))
	for i := range src {
		dst[i] = convEventAdminToRoomAdmin(src[i])
	}
	return
}

func convEventAdminToRoomAdmin(src EventAdmin) (dst RoomAdmin) {
	dst.UserID = src.UserID
	return
}
