// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package utils

import "github.com/gofrs/uuid"

func UuidUUIDIn(element uuid.UUID, set []uuid.UUID) bool {
	for _, v := range set {
		if element == v {
			// exist!
			return true
		}
	}
	return false
}
