on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  IMAGE_NAME: knoq

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u traPtitech -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build -t docker.pkg.github.com/traptitech/knoq/${IMAGE_NAME}:${IMAGE_TAG} .
      - name: Push image to GitHub Registry
        run: docker push docker.pkg.github.com/traptitech/knoq/${IMAGE_NAME}:${IMAGE_TAG}
      - name: Push image to GitHub Registry (latest)
        run: |
          docker tag docker.pkg.github.com/traptitech/knoq/${IMAGE_NAME}:$IMAGE_TAG docker.pkg.github.com/traptitech/knoq/${IMAGE_NAME}:latest
          docker push docker.pkg.github.com/traptitech/knoq/${IMAGE_NAME}:latest
